In [ ]:
# Install the required library AbcProjectCache
pip install "abc_atlas_access[notebooks] @ git+https://github.com/alleninstitute/abc_atlas_access.git"

In [1]:
# Restart the python kernel required after installing new packages
get_ipython().kernel.do_shutdown(restart=True)

{'status': 'ok', 'restart': True}

In [3]:
# Import necessary python libraries
from pathlib import Path
import anndata
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
from PIL import Image

In [1]:
# Import AbcProjectCache
from abc_atlas_access.abc_atlas_cache.abc_project_cache import AbcProjectCache

In [4]:
# Setup Cache by specifying a dictionary
download_base = Path('/Users/kexin/Desktop/project/data') # Change it to your own dictionary path
abc_cache = AbcProjectCache.from_cache_dir(download_base)

In [5]:
# Check the current data edition
abc_cache.current_manifest

'releases/20260415/manifest.json'

#### Using cells selected in the ABC Atlas with Gene Expression data
Combine the cells selected from the ABC Atlas with gene expression data and metadata

In [6]:
cell_metadata = abc_cache.get_metadata_dataframe(
    directory='MERFISH-C57BL6J-638850',
    file_name='cell_metadata',
    dtype={"cell_label": str},
)
cell_metadata.set_index('cell_label', inplace=True)
cell_metadata.head()[['brain_section_label', 'abc_sample_id']]

,brain_section_label,abc_sample_id
cell_label,,
1019171907102340387-1,C57BL6J-638850.37,c9881423-76a7-4835-ba8b-7942fd384b6b
1104095349101460194-1,C57BL6J-638850.26,aa815488-6487-4e47-8a5e-d82ac9933bc6
1017092617101450577,C57BL6J-638850.25,91ef7a85-8e3e-4410-8ee2-785788df3ebe
1018093344101130233,C57BL6J-638850.13,18991e17-fbd3-4ba0-9c60-1281f56ac520
1019171912201610094,C57BL6J-638850.27,5e155936-e40d-4c6b-8971-e7fb0079274b

In [17]:
# Change path location below to your own downloaded cells
downloaded_cells_path = Path('/Users/kexin/Desktop/project/data/ABC_Atlas_GABA_Left_NOT_33.csv')

abc_atlas_selection = pd.read_csv(downloaded_cells_path)
abc_atlas_selection.rename(
    columns={'Sample Id': 'abc_sample_id'},
    inplace=True
)
abc_atlas_selection.set_index('abc_sample_id', inplace=True)
abc_atlas_selection.head()

,Supertype,Section Label,Neurotransmitter Type,Anatomical Division,Cluster,Class,Anatomical Structure,Subclass,Anatomical Substructure
abc_sample_id,,,,,,,,,
3972ead9-6d82-4f4d-b04e-4172d7e14750,0830 PRT Tcf7l2 Gaba_2,C57BL6J-638850.33,GABA,MB,3612 PRT Tcf7l2 Gaba_2,20 MB GABA,NOT,202 PRT Tcf7l2 Gaba,NOT
d23ad692-7d66-46f4-925c-f3b093bf5fec,0830 PRT Tcf7l2 Gaba_2,C57BL6J-638850.33,GABA,MB,3610 PRT Tcf7l2 Gaba_2,20 MB GABA,NOT,202 PRT Tcf7l2 Gaba,NOT
07e642aa-ad94-4ace-8507-970feb650e4a,0855 SCs Dmbx1 Gaba_4,C57BL6J-638850.33,GABA,MB,3736 SCs Dmbx1 Gaba_4,20 MB GABA,NOT,207 SCs Dmbx1 Gaba,NOT
d2808ef5-6afd-4441-9686-66cbeea89d83,0856 SCs Dmbx1 Gaba_5,C57BL6J-638850.33,GABA,MB,3740 SCs Dmbx1 Gaba_5,20 MB GABA,NOT,207 SCs Dmbx1 Gaba,NOT
aab19f5a-3bf0-4e1a-9c8f-799fd39c2156,0875 SCsg Gabrr2 Gaba_4,C57BL6J-638850.33,GABA,MB,3824 SCsg Gabrr2 Gaba_4,20 MB GABA,NOT,213 SCsg Gabrr2 Gaba,NOT

In [18]:
selected_cells = cell_metadata.join(abc_atlas_selection, on='abc_sample_id', how='inner')
print(len(selected_cells))
selected_cells.head()

70

,brain_section_label,cluster_alias,average_correlation_score,feature_matrix_label,donor_label,donor_genotype,donor_sex,x,y,z,abc_sample_id,Supertype,Section Label,Neurotransmitter Type,Anatomical Division,Cluster,Class,Anatomical Structure,Subclass,Anatomical Substructure
cell_label,,,,,,,,,,,,,,,,,,,,
1018093344101440149-5,C57BL6J-638850.33,3585,0.504741,C57BL6J-638850,C57BL6J-638850,wt/wt,M,4.382204,4.566946,5.8,fd6704ae-a91a-45c7-a18d-f90fe11e19a5,0872 SCsg Gabrr2 Gaba_1,C57BL6J-638850.33,GABA,MB,3798 SCsg Gabrr2 Gaba_1,20 MB GABA,NOT,213 SCsg Gabrr2 Gaba,NOT
1018093344101590144-5,C57BL6J-638850.33,3144,0.610559,C57BL6J-638850,C57BL6J-638850,wt/wt,M,4.864482,4.384457,5.8,03f33b75-f8d5-41ac-beb7-34959f41e03a,0862 SCs Pax7 Nfia Gaba_4,C57BL6J-638850.33,GABA,MB,3758 SCs Pax7 Nfia Gaba_4,20 MB GABA,NOT,209 SCs Pax7 Nfia Gaba,NOT
1018093344101440215-1,C57BL6J-638850.33,3285,0.603020,C57BL6J-638850,C57BL6J-638850,wt/wt,M,4.433295,4.380681,5.8,77344fe1-e5d4-4805-b690-ab3ee7a7579a,0864 PRT Mecom Gaba_1,C57BL6J-638850.33,GABA,MB,3761 PRT Mecom Gaba_1,20 MB GABA,NOT,210 PRT Mecom Gaba,NOT
1018093344101280808,C57BL6J-638850.33,3250,0.696276,C57BL6J-638850,C57BL6J-638850,wt/wt,M,4.224730,4.671702,5.8,90247422-947d-47f6-a43d-65b06564aa03,0832 PRT Tcf7l2 Gaba_4,C57BL6J-638850.33,GABA,MB,3627 PRT Tcf7l2 Gaba_4,20 MB GABA,NOT,202 PRT Tcf7l2 Gaba,NOT
1018093344101280575-6,C57BL6J-638850.33,3415,0.577060,C57BL6J-638850,C57BL6J-638850,wt/wt,M,4.079257,4.747042,5.8,3125c8a9-4f5c-491e-b3a8-d1323ecdaecc,0830 PRT Tcf7l2 Gaba_2,C57BL6J-638850.33,GABA,MB,3611 PRT Tcf7l2 Gaba_2,20 MB GABA,NOT,202 PRT Tcf7l2 Gaba,NOT

In [19]:
gene = abc_cache.get_metadata_dataframe(directory='MERFISH-C57BL6J-638850', file_name='gene').set_index('gene_identifier')
gene.head()

,gene_symbol,transcript_identifier,name,mapped_ncbi_identifier
gene_identifier,,,,
ENSMUSG00000026778,Prkcq,ENSMUST00000028118,"protein kinase C, theta",NCBIGene:18761
ENSMUSG00000026837,Col5a1,ENSMUST00000028280,"collagen, type V, alpha 1",NCBIGene:12831
ENSMUSG00000001985,Grik3,ENSMUST00000030676,"glutamate receptor, ionotropic, kainate 3",NCBIGene:14807
ENSMUSG00000039323,Igfbp2,ENSMUST00000047328,insulin-like growth factor binding protein 2,NCBIGene:16008
ENSMUSG00000048387,Osr1,ENSMUST00000057021,odd-skipped related transcription factor 1,NCBIGene:23967

In [23]:
# Load the anndata, cell by gene matrix.
file_path = abc_cache.get_file_path(
    directory='MERFISH-C57BL6J-638850-sections',
    file_name='C57BL6J-638850.33/log2'
)
adata = anndata.read_h5ad(file_path, backed='r')
# Create a landing Pandas DataFrame for the data.
selected_cell_gene_data = pd.DataFrame(index=selected_cells.index,
                                       columns=adata.var.index)

# Find the subset of cells we selected in the full matrix.
mask = adata.obs.index.isin(selected_cells.index)
# Fill our DataFrame with the
selected_cell_gene_data.loc[selected_cells.index, adata.var.index] = adata.X[mask].toarray()
selected_cell_gene_data.columns = gene.gene_symbol

In [25]:
# Check the gene expression matrix of the selected cells
selected_cell_gene_data.head()

gene_symbol,Prkcq,Col5a1,Grik3,Igfbp2,Osr1,Syt6,Cntnap3,Lmo3,Ntn1,Otp,...,Blank-16,Blank-32,Blank-18,Blank-4,Blank-28,Blank-33,Blank-34,Blank-45,Blank-23,Blank-48
cell_label,,,,,,,,,,,,,,,,,,,,,
1018093344101440149-5,0.0,0.0,0.0,0.73695,0.0,0.0,0.0,0.73695,0.0,0.0,...,0.0,0.73695,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1018093344101590144-5,0.0,0.0,0.0,0.735063,0.735063,0.0,0.735063,0.0,0.735063,0.0,...,0.0,0.0,0.0,0.0,0.0,0.735063,0.0,0.0,0.0,0.0
1018093344101440215-1,0.0,0.0,0.978516,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.978516,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1018093344101280808,0.896871,0.0,2.981156,0.896871,0.0,0.896871,2.153187,0.896871,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.896871,0.0
1018093344101280575-6,0.0,0.0,1.261199,1.261199,0.0,3.229848,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
# Save the gene matrix to local position
selected_cell_gene_data.to_csv("/Users/kexin/Desktop/project/data/selected_left_NOT_33_log2_expression.csv") # Change the path and the file name